version = 1

[*]
ctx-size = 65536

flash-attn = on

cache-type-k = q8_0
cache-type-v = q8_0

threads = 20

fit-target = 256

batch-size = 2048
ubatch-size = 512
parallel = 1

no-mmproj-offload = 1 ; keep mmproj in system memory

timeout = 10000 ; http timeout, 10 t/s for 100,000 tokens. I don't think this works.
no-ui = 1

reasoning-budget-message = "... thinking budget exceeded, let's answer now."

; defaults:
temp = 0.80
top-p = 0.95
top-k = 40
min-p = 0.05
top-n-sigma = -1.0
xtc-probability = 0.0
xtc-threshold = 0.10
typical-p = 1.00
repeat-last-n = 64
repeat-penalty = 1.00
presence-penalty = 0.0
frequency-penalty = 0.0

[gemma-4-26b-128k]
model = /mnt/mine/models/llm/gemma-4-26B-A4B-it-UD-IQ4_NL.gguf
ctx-size = 131072
[gemma-4-26b-256k]
model = /mnt/mine/models/llm/gemma-4-26B-A4B-it-UD-IQ4_NL.gguf
ctx-size = 262144

; gpt-oss 20b

[gpt-oss-20b-64k]
model = /mnt/mine/models/llm/gpt-oss-20b-UD-Q6_K_XL.gguf
ctx-size = 65536 
temp = 1.00
top-p = 1.00
top-k = 0
[gpt-oss-20b-128k]
model = /mnt/mine/models/llm/gpt-oss-20b-UD-Q6_K_XL.gguf
ctx-size = 131072
temp = 1.00
top-p = 1.00
top-k = 0

; Qwen 3.6
;
; Thinking mode - "precise coding tasks" https://unsloth.ai/docs/models/qwen3.6#thinking-mode
;temp = 0.60
;top-p = 0.95
;top-k = 20
;min-p = 0.00
;presence-penalty = 0.0
;repeat-penalty = 1.00 ; disabled

[qwen3.6-35b-Coding-128k-MTP-US-UD-Q4-K_M]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-MTP-US-UD-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
ctx-size = 131072
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-128k-Multi-US-UD-Q4-K_M]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q4_K_M.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 131072
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-128k-Multi-US-UD-Q5-K_S]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q5_K_S.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 131072
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-128k-Multi-US-UD-Q5-K_XL]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q5_K_XL.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 131072
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-256k-Multi-US-UD-Q5-K_XL]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q5_K_XL.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 262144
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-64k-Multi-US-UD-Q6-K]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q6_K.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 65536
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-128k-Multi-US-UD-Q6-K]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q6_K.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 131072
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.6-35b-Coding-256k-Multi-US-UD-Q6-K]
model = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-UD-Q6_K.gguf
mmproj = /mnt/mine/models/llm/Qwen3.6-35B-A3B-US-mmproj-BF16.gguf
ctx-size = 262144
temp = 0.60
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00


; Qwen 3.8

[qwen3.8-27B-Coding-Multi-ISTA-GSQ-RCO-IQ3_XXS]
model = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-GSQ-RCO-IQ3_XXS.gguf
mmproj = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-mmproj-BF16.gguf
ctx-size = 130000
cache-type-k = q8_0
cache-type-v = q4_0
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.8-27B-Coding-64k-Multi-ISTA-GSQ-RCO-IQ3_XXS]
model = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-GSQ-RCO-IQ3_XXS.gguf
mmproj = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-mmproj-BF16.gguf
ctx-size = 65565
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.8-27B-Coding-100k-Multi-ISTA-GSQ-RCO-IQ3_XXS-Q84]
model = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-GSQ-RCO-IQ3_XXS.gguf
mmproj = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-mmproj-BF16.gguf
ctx-size = 100000
cache-type-k = q8_0
cache-type-v = q4_0
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00

[qwen3.8-27B-Coding-64k-Multi-ISTA-GSQ-RCO-IQ3_S]
model = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-GSQ-RCO-IQ3_S.gguf
mmproj = /mnt/mine/models/llm/Qwen3.8-27B-ISTA-mmproj-BF16.gguf
ctx-size = 65565
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.00